rendezvous_server = '95.81.114.151:21116'
nat_type = 1
serial = 0
unlock_pin = ''
trusted_devices = '00p3pboc0M9FI68U6I5FNOHfmo'

[options]
allow-remove-wallpaper = 'Y'
custom-rendezvous-server = '95.81.114.151'
av1-test = 'Y'
access-mode = 'full'
local-ip-addr = '192.168.88.12'
key = 'cuv7RvwfD9a5K8TnGnpbkBLfbqhQCju4RcvXjmozJjo='
relay-server = '95.81.114.151'
direct-server = 'Y'
